export function mountUI(){
 document.querySelector('#app')!.innerHTML=`
 <main id="experience"><canvas id="viewport" aria-label="宇宙ステーションの3Dビュー"></canvas><div class="vignette"></div>
 <header><a class="brand" href="#" aria-label="Aether ホーム"><svg viewBox="0 0 48 48"><ellipse cx="24" cy="24" rx="22" ry="8" transform="rotate(-30 24 24)"/><path d="M14 36 24 10 34 36M18 27h12"/></svg><span>AETHER<small>ORBITAL STATION</small></span></a><div class="header-right"><span class="live"><i></i> ALL SYSTEMS NOMINAL</span><button id="sound" class="icon-button" title="環境音の切り替え" aria-label="環境音をオンにする">♪<span id="sound-label">OFF</span></button><button id="help" class="icon-button" aria-label="操作ガイド">?</button></div></header>
 <section id="landing"><div class="eyebrow"><span class="line"></span> LOW EARTH ORBIT / 408 KM</div><h1>A home<br>above <em>Earth.</em></h1><p>地球を離れて、地球を感じる。<br>あなたの軌道上の一日が、ここから始まる。</p><button id="enter" class="primary" disabled><span>ステーションに入る</span><span>↗</span></button><button id="exterior" class="text-button">外観を自由に見る <span>→</span></button><div class="landing-note"><span>01—04</span> 展望室・居住区・研究室・機関室</div></section>
 <div id="station-label"><span class="cross">+</span><div>AETHER / STATION 01<small>35° 41′ N &nbsp; 139° 41′ E</small></div></div>
 <footer id="landing-footer"><span>HUMAN EXPLORATION PROGRAM <b>—</b> EST. 2086</span><div><span>VELOCITY <b>7.66 <small>KM/S</small></b></span><span>ORBIT PERIOD <b>92.6 <small>MIN</small></b></span><span>CREW <b>12 <small>ON BOARD</small></b></span></div></footer>
 <div id="loading"><span id="load-label">ステーションを準備しています</span><div><i id="load-bar"></i></div></div>
 <section id="hud" hidden><div class="location"><span id="location-no">01 / DECK A</span><h2 id="location-name">展望室</h2><p id="location-en">CUPOLA OBSERVATORY</p></div><div id="objective"><span class="tiny-label">EXPLORATION LOG</span><div id="objective-text">地球を眺めて、ステーションを探索する</div><div class="progress-dots"><i></i><i></i><i></i><i></i></div></div><nav id="tools"><button id="map-button" title="ステーションマップ [M]">▦ <span>マップ</span><kbd>M</kbd></button><button id="outside-button" title="外観カメラ [V]">◎ <span>外観</span><kbd>V</kbd></button><button id="photo-button" title="写真撮影 [P]">▣ <span>撮影</span><kbd>P</kbd></button><button id="settings-button" title="設定">⚙ <span>設定</span></button></nav><div id="telemetry"><span><i class="status-dot"></i> <b id="power-value">96</b>% <small>POWER</small></span><span><b id="gravity-value">1.0</b> <small>G</small></span><span><b>21.0</b>% <small>O₂</small></span></div><div id="walk-hint"><kbd>W A S D</kbd> 移動 <b>·</b> ドラッグで視点 <b>·</b> <kbd>E</kbd> 操作 <b>·</b> <kbd>F</kbd> マウス固定</div></section>
 <div id="crosshair" hidden><i></i><i></i></div><button id="interact" hidden><kbd>E</kbd><span><strong></strong><small></small></span></button>
 <div id="orbit-help" hidden>ドラッグで回転 <b>·</b> ホイールでズーム <button id="return-inside">ステーションに入る ↗</button></div>
 <div id="toast" role="status" aria-live="polite"></div>
 <div id="touch-controls" hidden><div class="dpad"><button data-move="KeyW" aria-label="前へ">↑</button><button data-move="KeyA" aria-label="左へ">←</button><button data-move="KeyS" aria-label="後ろへ">↓</button><button data-move="KeyD" aria-label="右へ">→</button></div><button id="touch-action">操作</button></div>
 <dialog id="map-dialog"><div class="dialog-head"><div><span class="eyebrow">STATION DIRECTORY</span><h2>ステーションマップ</h2></div><button class="close" aria-label="閉じる">×</button></div><p class="muted">行き先を選んで移動できます。各区画は通路でもつながっています。</p><div class="deck-map"><div class="map-spine"></div><button data-room="observatory" class="map-room cupola"><small>01 / DECK A</small><strong>展望室</strong><span>地球観測・窓シャッター</span></button><button data-room="habitat" class="map-room habitat"><small>02 / DECK B</small><strong>居住区</strong><span>キャビン・照明制御</span></button><button data-room="lab" class="map-room lab"><small>03 / DECK B</small><strong>研究室</strong><span>植物栽培・太陽電池制御</span></button><button data-room="engineering" class="map-room engineering"><small>04 / DECK C</small><strong>機関室</strong><span>リアクター・人工重力</span></button></div><p class="map-legend"><i class="status-dot"></i> 訪問済み <span>ハッチに近づき E で開閉</span></p></dialog>
 <dialog id="help-dialog"><div class="dialog-head"><div><span class="eyebrow">WELCOME ABOARD</span><h2>軌道上での過ごし方</h2></div><button class="close" aria-label="閉じる">×</button></div><div class="help-grid"><p><kbd>W A S D</kbd><span>歩く / <b>Shift</b> で速く移動</span></p><p><kbd>DRAG</kbd><span>画面をドラッグして見回す</span></p><p><kbd>F</kbd><span>マウス固定 / <b>Esc</b> で解除</span></p><p><kbd>E</kbd><span>近くのハッチ・設備を操作</span></p><p><kbd>M</kbd><span>マップを開く</span></p><p><kbd>V</kbd><span>外観と内部を切り替える</span></p><p><kbd>P</kbd><span>UI なしの写真を保存</span></p><p><kbd>SPACE / Q</kbd><span>無重力時の上昇 / 下降</span></p></div><div class="hint-box">まずは展望室の左右にあるコンソールを操作してみましょう。機関室で人工重力を切ると、浮遊しながら移動できます。</div><button class="primary close-help">探索を始める ↗</button></dialog>
 <dialog id="settings-dialog"><div class="dialog-head"><div><span class="eyebrow">EXPERIENCE SETTINGS</span><h2>表示と環境</h2></div><button class="close" aria-label="閉じる">×</button></div><label class="setting">描画品質<select id="quality"><option value="high">高品質</option><option value="medium">標準</option><option value="low">軽量</option></select></label><label class="setting">視点の感度<input id="sensitivity" type="range" min="0.5" max="2" step="0.1" value="1"></label><label class="setting">軌道の時間<select id="orbit-speed"><option value="1">リアルタイム</option><option value="20">20 倍速</option><option value="100">100 倍速</option></select></label><label class="setting">環境音<input id="audio-toggle" type="checkbox"></label><div class="credits">PBR materials: <a href="https://polyhaven.com" target="_blank" rel="noreferrer">Poly Haven (CC0)</a><br>Earth / stars: <a href="https://www.solarsystemscope.com/textures/" target="_blank" rel="noreferrer">Solar System Scope / INOVE (CC BY 4.0)</a><br>Night imagery: NASA / Three.js examples<br>Original station model authored in Blender<br><a href="./viewer.html?station=1" target="_blank" rel="noreferrer">WebGPU スタジオビューアを開く ↗</a><br><small>架空の研究ステーションです。軌道数値は演出用で、宇宙飛行の訓練用シミュレーションではありません。</small></div></dialog>
 <div id="fatal" hidden><h2>3D ビューを開始できませんでした</h2><p></p><button onclick="location.reload()">再読み込み</button></div>
 </main>`;
}
export function toast(message:string){const el=document.querySelector('#toast')!;el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>el.classList.remove('show'),3500);}
let toastTimer=0;
